- hosts: all
  
  tasks:
   
   - name: Generate hosts file
     lineinfile: dest=/etc/hosts
                 regexp='.*{{ item }}$'
                 line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
                 state=present            
     when: hostvars[item].ansible_default_ipv4.address is defined
     with_items: "{{groups['all']}}"
     become: true
     
   #- name: Set hostname
   #  hostname: name="{{inventory_hostname}}"
   #  become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Download git repository
     become: true
     git:
      repo: 'https://github.com/sztoor/model_serving.git'
      dest: /model_serving 
      
   - name: Change ownership of a directory
     become: true
     file:
      path: /technical-training
      state: directory
      recurse: yes
      owner: appuser
      group: appuser

- hosts: prodserver
 
  vars_files:
   - setup_var.yml  
  
  tasks:  
   - name: Extra packages
     apt: pkg={{item}} state=latest update_cache=true 
     with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
     become: true  

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Add Docker repository key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
     become: true

   - name: Add Docker repository 
     command: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
     become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true
  
   # Workaround pip issue with MTU mismatch, see: https://github.com/docker/docker.github.io/pull/9249/files
   # MTU for SNIC is 1450, Docker default is 1500. Override so that Docker matches the host.
   # We create the config file before installing, to avoid any need to restart the docker daemon.
   - name: Create Ansible docker config directory.
     become: true
     file:
       path: "/etc/docker"
       state: directory

   - name: Create Ansible docker file to configure Docker MTU to match SNIC for pip issue
     become: true
     copy:
       dest: "/etc/docker/daemon.json"
       content: |
        {
          "mtu": 1450
        }

   - name: Install Docker  
     apt: pkg=docker-ce state=present update_cache=true allow_unauthenticated=yes
     become: true

   - name: Download docker-compose 
     become: yes
     get_url:        
      url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
      dest: /usr/local/bin/docker-compose
      mode: +x  

   - name: Building containers
     become: true
     shell: docker build .
     args: 
      chdir: /model_serving/ci_cd/production_server

   - name: Running containers
     become: true
     shell: docker-compose up -d 
     args: 
      chdir: /model_serving/ci_cd/production_server 

- hosts: devserver
  
  vars_files:
   - setup_var.yml

  tasks:
   - name: Extra packages
     apt: pkg=python3-pip state=latest update_cache=true  
     become: true

   - name: Install ML packages
     become: true
     pip: 
      name: tensorflow==2.5.3, keras==2.4.1, numpy, future
