name: CI

on:
  push:
  schedule:
    - cron: "12 3 * * 5" # every friday at 03:14      

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Testing model serving code for assignment-2 of DE-II course.
      run: |
        sudo apt update
        sudo apt upgrade -y 
        sudo apt install -y python3-pip python3-dev build-essential rabbitmq-server
        sudo pip3 install celery tensorflow==2.10.0 amqp flask==2.3.1 future numpy
        git clone https://github.com/sztoor/model_serving.git /tmp/model_serving
    
        timeout --preserve-status 10 celery --workdir=/tmp/model_serving/single_server_without_docker/production_server/ -A workerA worker --detach --loglevel=debug --concurrency=1 -n wkr1@backend
        timeout --preserve-status 5 python3 /tmp/model_serving/single_server_without_docker/production_server/app.py --host=0.0.0.0 --port=5100
